server:
  port: 8080
  shutdown: graceful
spring:
  cloud:
    gateway:
      routes:
        - id: redirect
          uri: lb://redirect
          predicates:
            - Path=/r/**
        - id: shortener
          uri: lb://shortener
          predicates:
            - Path=/urlmanage/addurl
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/oauth/token,/.well-known/jwks.json
        - id: manager
          uri: lb://manager
          predicates:
            - Path=/urlmanage/findurl,/urlmanage/deleteurl
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/register
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
