server:
  port: 8080
  shutdown: graceful
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://gateway:8080/.well-known/jwks.json
  data:
    mongodb:
      uri: mongodb://mongo:27017/short_url_db
  redis:
    host: redis-cache
    port: 6379
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
