server:
  port: 0
  shutdown: graceful
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://47.102.118.113:8080/.well-known/jwks.json
  data:
    mongodb:
      uri: mongodb://47.101.191.189:27017/short_url_db
  redis:
    host: 47.101.191.189
    port: 6380
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: *
