spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: admin-service
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        health-check-critical-timeout: 20s
        instanceId: admin-service:8051
        enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/.well-known/jwks.json

  datasource:
    url: jdbc:mysql://localhost:3306/shorturl?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: chenyang
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379 

management:
  endpoints:
    web:
      exposure:
        include: "*"