server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/short_url_db?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    database: mysql
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
management:
  endpoints:
    web:
      exposure:
        include: "*"
