server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/short_url_db?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    database: mysql
  redis:
    host: localhost
    port: 6380
  data:
    mongodb:
      uri: mongodb://localhost:27017/short_url_db
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  cache:
    type: redis
    redis:
      cache-null-values: false
      use-key-prefix: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
