server:
  port: 0
spring:
  jpa:
    database: mysql
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/short_url_user_db?serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
