server:
  port: 8080
  shutdown: graceful
spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/short_url_db
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
