server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://mysql:3306/short_url_db?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    database: mysql
  redis:
    host: redis
    port: 6379
  data:
    mongodb:
      uri: mongodb://mongodb:27017/short_url_db
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /
    port: 5672
  cache:
    type: redis
    redis:
      cache-null-values: false
      use-key-prefix: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
