server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/short_url_db?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    database: mysql
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "*"
