server:
  port: 0
  shutdown: graceful
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  data:
    mongodb:
      uri: mongodb://localhost:27017/short_url_db
  redis:
    cluster:
      nodes:
        - localhost:6379
        - localhost:6380
        - localhost:6381
