server:
  port: 0
  shutdown: graceful
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/short_url_db
  redis:
    cluster:
      nodes:
        - localhost:6379
        - localhost:6380
        - localhost:6381
