spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shorturl?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: register-service
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        health-check-critical-timeout: 20s
        instanceId: register-service:8031
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
