spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: statistic-service
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        health-check-critical-timeout: 20s
        instanceId: ${spring.application.name}:${server.port}
        enabled: true
    stream:
      rabbit:
        bindings:
          dpb-exchange:
            consumer:
              prefetch: 30
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
  datasource:
    url: jdbc:mysql://localhost:3306/shorturl?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"
